version: '3.8'
services:
  android:
    build: .
    ports:
      - "6080:6080"
  backend:
    build: ../backend
    ports:
      - "4000:4000"
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
