name: Deploy to ECS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 \
            | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Build, tag, and push docker image
        run: |
          docker build -t cloud-android .
          docker tag cloud-android:latest <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-2.amazonaws.com/cloud-android:latest
          docker push <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-2.amazonaws.com/cloud-android:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster cloud-android-cluster \
            --service cloud-android-service \
            --force-new-deployment
